version: "2"
services:
    postgres:
      image: postgres:9.4
      volumes:
          - ~/data/db-designer-svg/postgres:/var/lib/postgresql/data
      env_file: .env

    django:
      build: .
      image: benthomasson/db-designer-svg
      user: django
      links:
        - postgres
      command: /runserver.sh
      env_file: .env
      volumes:
          - .:/app
          - static-files:/app/staticfiles

    nginx:
      build: ./compose/nginx
      links:
        - django
      ports:
        - "0.0.0.0:8001:80"
      volumes:
          - static-files:/app/staticfiles
volumes:
    static-files:
