# Generated by Django 2.0.8 on 2018-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004__auto_20180830_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='column',
            name='related_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='uuid',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
