# Generated by Django 2.0.8 on 2018-09-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_auto_20180912_2000'),
    ]

    operations = [
    ]
